### ISSUE TITLE
Typo in "Linear Algebra Review.pdf" page 3

### ISSUE THREAD

**Issue by yxords** [scpd-proed/General_Handouts#1]
Second sentence, "We denote the ith row of A by a^T ..." probably should be "... by a^T_i ..."

**Comment by abanuelo** [comment]
Added changes to master of General_Handouts. Thanks for catching. Here is screenshot of the suggested edit. Nice catch! 
<img width="575" alt="Screen Shot 2021-04-13 at 11 01 34 PM" src="https://user-images.githubusercontent.com/32311654/114661797-710e4280-9cac-11eb-89a9-66380ba718d2.png">
